name: s3 Deploy
on:
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  statuses: write
  actions: read
  contents: read

jobs:
  call-vpc-workflow:
    uses: ./.github/workflows/deploy.yaml
    with:
      work-dir: "environments/s3"
      aws-region: "us-west-2"
    secrets:
      CI_ROLE: ${{ secrets.CI_ROLE }}
      JF_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      JF_URL: ${{ secrets.JF_URL }}
